### PR TITLE
VS Code config improvements

### PR DESCRIPTION
**Pull request by coldacid**
Makes things just a little less painful when using Visual Studio Code for hacking on iGame.

### CODE REVIEW

**Comment by walkero-gr** [comment]
These vscode changes apply to all environments, even on docker? 
Just a matter of discussion, to figure out if we should keep these configuration files or get rid of them, since they are closely depending on each developer environment. 

What do you think?

**Comment by coldacid** [comment]
I don't think Docker is relevant in this situation, unless you're running Visual Studio Code from inside a Docker container. Other than the .editorconfig changes (which merely brings that file more in line with the reality of how the code has been formatted to date) there are no changes here that affect anything outside of VS Code itself. And even then the only thing that might be different between each developer's environment are the include paths inside c_cpp_properties.json and even the changes I made there were just reordering the existing items so that IntelliSense would resolve the VBCC target headers last (resolving them first tended to cause IntelliSense to choke and die).

I think it's fine to keep the .vscode directory and the files inside it.

**Comment by walkero-gr** [comment]
@coldacid Thanks for the explanation. Actually I do use VSCode inside the containers, because like that I can have the IntelliSense work just fine and I keep my host machine clean and isolated. And if I need to work at an other machine, I will be able to continue my work with no issues.

**Comment by coldacid** [comment]
@walkero-gr: You might want to pull my branch and try it out, but it should work just fine in VS Code in Docker.

The biggest improvement is probably the includePaths reordering in c_cpp_properties.json. It should get rid of "#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit" errors from IntelliSense inside VS Code.

**Review by walkero-gr — APPROVED** [review]

**Pull request merged**
