### PR TITLE
Added a Balance object

### PR DESCRIPTION
**Pull request by walkero-gr**
I added a balance object between the Games list and the right sidebar. Also, removed rows and columns defined, as these are necessary when you have two dimensional groups, which this is not the case. This might make the window draw a little bit faster on slow machines.

The new balance works fine on both MUI 3.8 and MUI 5.0

testenvamigaos31-real-2005222356-01
testenvamigaos314a1200mui3-real-2005222356-01

### CODE REVIEW

**Comment by coldacid** [comment]
This seems like it'll be really useful when Guigfx isn't being used and icons from one game to another have different sizes.

**Comment by walkero-gr** [comment]
@coldacid 
If you don't have a screenshot this is not locked and can help on small screens. On the other hand, even if it is locked right now, this doesn't do any harm.
For sure, to get more benefits from the balance, the screenshot should be scalable. Maybe in a future PR. :D

**Comment by coldacid** [comment]
Yeah, that's exactly what I determined from my testing. It's definitely helpful, and that behavior is quite reasonable.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by walkero-gr** [comment]
DO NOT MERGE IT YET. I need to make some more changes on this one, so the groups weights are saved on application quit. WIP

**Comment by walkero-gr** [comment]
With the latest commit https://github.com/MrZammler/iGame/pull/79/commits/ef3e9d16746346ae3a604870729448a77e36bfc1
I added the feature to automatically save the position of the balance on app quit and restore it on load. This means that the balancing position will be remembered after a user closes iGame.

This unfortunately works only on MUI 5, since this is not supported on MUI 3.x.

@MrZammler From my side this PR is finished in case you want to merge it.

**Pull request merged**
