### PR TITLE
Use flexcat to regenerate catalog source files during build

### PR DESCRIPTION
**Pull request by coldacid**
It feels safer to me to treat `iGameStrings.cd` as the source of truth for translatable strings instead of `iGameStrings_cat.c` and `iGameStrings_cat.h`. This PR enforces the cd file as source of truth by adding flexcat into the build plan, generating the C source and header files automatically during build.

It *does* require that the flexcat executable is available on the building platform in the path. However, since flexcat is available for AmigaOS, Linux, and Windows, that shouldn't be a problem.

`iGameStrings_cat.c` and `iGameStrings_cat.h` are deleted and added to `.gitignore` to prevent changes being made to those files that aren't in `iGameStrings.cd`. I can back that out, but it would run the risk of changes in the C source and header being undone as soon as anyone changes the cd file.

### CODE REVIEW

**Comment by walkero-gr** [comment]
@coldacid Great stuff here. I agree that the iGameStrings.cd should be the file we need to use.
Just a question. If someone doesn't have the flexcat installed and in path, the build continues or fails?

Can you also remove from the PR the files that the bits are changed?

**Comment by coldacid** [comment]
@walkero-gr the build would fail if flexcat isn't installed, due to iGameStrings_cat.c and iGameStrings_cat.h being removed from the repository. Since iGameStrings_cat.c is listed as a dependency for all iGameStrings_cat*.o and iGameStrings_cat.h is listed as one for all src/iGameGUI*.o, make will try to call flexcat to generate those files and fail if flexcat is not on the path.

Even if we don't delete iGameStrings_cat.* from the repository, any changes to iGameStrings.cd itself will cause make to attempt to regenerate the files since the timestamp on iGameStrings.cd would be newer than the generated source files, with the same failure result if flexcat isn't available.

We'll need to update the compilation instructions in the wiki pages along with this PR.

Regarding the file permission changes in this PR, I can certainly back those out, but it'd be a good idea to put those changes in master anyway. The commit itself should probably just be cherry-picked into master. I'll set a branch on bc73eb0 and rebase the remaining commits off of master.

**Comment by coldacid** [comment]
Branch updated to remove the UNIX permissions commit.

**Comment by coldacid** [comment]
I found a related issue as well. The original iGameStrings_cat.c file, along with the one generated by flexcat, both cause the catalog initialization code to look for iGameStrings.catalog in the appropriate locale catalogs drawer instead of iGame.catalog. To fix this, we should rename iGameStrings.cd to iGame.cd and make related changes for the functions that will be similarly renamed in the generated source file. @walkero-gr @MrZammler would you want me to pack that in to this PR, or file it as a separate bug with its own PR?

**Comment by coldacid** [comment]
@MrZammler @walkero-gr: I've fixed up the merge conflicts. I've also set up another PR that builds on this one to fix up the problems with actually loading catalogs.

**Comment by walkero-gr** [comment]
@coldacid Is this still necessary, or is it covered by #104? Should we close this one?

**Comment by coldacid** [comment]
@walkero-gr let me verify, but I'm pretty sure that #104 builds on top of this branch, so merging it should automatically complete this PR as merged.

**Comment by coldacid** [comment]
@walkero-gr #104 does indeed supercede this PR. We can merge the latter and it'll include all of this.

**Comment by walkero-gr** [comment]
Closed because this work is included in #104

**Pull request closed without merging**
