### PR TITLE
Cpu in version strings

### PR DESCRIPTION
**Pull request by walkero-gr**
With these changes the version.h file is refactored, so to:
1. Show the CPU/OS the specific binary compiled for. This uses a define names CPU_VERS where the values are 68000, 68030, 68040, 68040, AmigaOS4 and MorphOS. This is shown at the **About** window text and with the "version" command at the shell. Attached some screenshots
2. The version is set by defines as well. There are MAJOR_VERS, MINOR_VERS and BETA_VERS. This can be set on compiling as well, and change the VERSION STRING. This is set like that, having in mind the CI/CD setup, where the version values can also be set on ENVironment variables, and take their values from release tags. Something for the future.

igame_os4_version
igame_os3_version
igame_os3_about
igame_os4_about

### CODE REVIEW

**Comment by coldacid** [comment]
Makefile, Makefile.docker, and Makefile.linux all contain a `release` target which overwrites the contents of version.h before compiling each platform target. Those lines should be removed from these files, and probably replaced by version variables at the top of each makefile to be `-D`'d in.

**Comment by walkero-gr** [comment]
@coldacid 
Have a look at https://github.com/walkero-gr/iGame/pull/15/files. These changes are for the CI/CD of the project as I have it in my fork. 
With these changes I can create a new tag on my fork, and as soon as I do that, the drone CI/CD server starts running, creates the builds for each CPU and OS, package them and deploys the file into my repo releases. The whole work takes less than a minute.
Also, the version and the date of the iGame is defined totally by the tag. This means that the deployment is fully automated now. 
I will talk with @MrZammler to see if he is interested to use that methodology on the original repo and deploy iGame the same way.
Unfortunately, the rest of the Makefiles cannot include the same code like the Makefile.docker, except the definition of the RELEASE_DATE. I will update this PR with some of these changes.

**Comment by coldacid** [comment]
@walkero-gr that's such a different kettle of fish that it should be its own PR separate from this. In the meantime I've done a rebase of your Cpu-in-versions-pr branch on top of the current master, which resolves the merge conflict issue without the noise of counter-merging master into your original PR branch as https://github.com/walkero-gr/iGame/pull/13 provided. Perhaps https://github.com/coldacid/iGame/tree/Cpu-in-versions-pr should be merged in here for now, and the CI/CD stuff later.

**Comment by coldacid** [comment]
@walkero-gr you might want to cherry-pick https://github.com/coldacid/iGame/commit/98959d2757ca8b2d73bba909dce29c527a6aa7db from my repo; it gets the current date and injects it into the version string instead of using the fixed "2019-05-03" date.

**Comment by walkero-gr** [comment]
@coldacid Thanks for that. Actually I have an automated way to add that at my repo (https://github.com/walkero-gr/iGame/blob/develop/Makefile.docker#L40) which also grabs the date and passes that into the code while it compiles. Maybe in the future we can all of these merged. That reminds me that I need to update this PR to get rid of these conflicts.

**Comment by coldacid** [comment]
@walkero-gr your `RELEASE_DATE` define looks the same as my `VERS_DATE` define. I should probably adapt my code to how you have it, updating the other makefiles to set `RELEASE_DATE` instead of `VERS_DATE` and using your version of version.h to set the default "date".

**Comment by coldacid** [comment]
@walkero-gr if you squash https://github.com/coldacid/iGame/commit/98959d2757ca8b2d73bba909dce29c527a6aa7db and https://github.com/coldacid/iGame/commit/72a084c8e2f5993dec16fa282ebbcacfc4c45fa2 together into your branch, it should Just Work™ with your branch's code.

I've done some clean-up work on the general makefiles as well to bring them more in line with your `Makefile.docker`, especially with the release and clean-release targets. I've put that in a separate branch https://github.com/coldacid/iGame/tree/cleaner-make-and-release for now, and it should probably get integrated as well when your build stuff gets integrated into mainline.

**Comment by walkero-gr** [comment]
@coldacid Thanks for the work you did. I like to keep PRs as small as possible, because they are easier to code reviewed and merged. This one adds the CPU at the string version. As soon as this is merged by @MrZammler it is better to create a new one that adds the date as well. Do you agree?

**Comment by coldacid** [comment]
@walkero-gr my own philosophy is that commits themselves should be small and self-contained, but a PR can be any size so long as they cover a single feature change. I consider my work to be part of the build-defined version string "feature" so in my eyes it seems reasonable to add it to this PR. However, it's your PR, so if you'd rather my changes be PR'd separately I can live with that.

**Comment by walkero-gr** [comment]
@MrZammler Resolved all the conflicts based on the latest merges on master

**Pull request merged**
